project:
  type: website

website:
  title: "Chunyu Wang"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - text: 'Publications'
        href: publications
      - text: 'Teaching'
        href: teachings
      - text: 'blogs'
        href: blogs
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual


